version: "2"
services:
  api:
    image: samualpay/add_one_club-backend:latest
    restart: always
    env_file:
      - ./local.env
    ports:
      - "8080:8080"
    volumes:
      - ./volume:/opt/workdir/dist/public/images
